export const SETTINGS_LABELS = {
	synthName: 'Name',
	midiSlotA: 'Slot A',
	midiSlotB: 'Slot B',
	midiSlotC: 'Slot C',
	midiSlotD: 'Slot D',
	midiGlobal: 'Global',
	midiSysex: 'SysEx ID',
	midiLocal: 'Local',
	midiPrgCh: 'Prog Change',
	midiClkSend: 'Clock Send',
	midiClkReceive: 'Clock Receive',
	tuningSemi: 'Semitones',
	tuningCent: 'Cents',
	pedalPolarity: 'Polarity',
	pedalGain: 'Gain',
	perfName: 'Name',
	bpm: 'BPM',
	clockRunning: 'Clock Running',
	rangeEnable: 'KB Split',
	slotActive: 'Active',
	slotKey: 'Key',
	slotHold: 'Hold',
	slotRangeLower: 'Lower',
	slotRangeUpper: 'Upper',
	patchName: 'Name',
	patchCategory: 'Category',
	patchVol: 'Volume',
	patchActiveMuted: 'Active',
	patchGlide: 'Glide',
	patchGlideTime: 'Glide Time',
	patchBend: 'Bend',
	patchSemi: 'Semitones',
	patchVibrato: 'Vibrato',
	patchCents: 'Vibrato Cents',
	patchRate: 'Vibrato Rate',
	patchArpeggiator: 'Arpeggiator',
	patchArpTime: 'Arp Time',
	patchArpType: 'Arp Type',
	patchOctaveShift: 'Octave Shift',
	patchSustain: 'Sustain',
	patchOctaves: 'Octaves',
	editorPath: 'Browser Path',
	editorHiddenModules: 'Show Hidden Modules',
} as const;
